### ISSUE TITLE
Is GWT 2.7 supported?

### ISSUE THREAD

**Issue by JakeSummers** [google/gwteventbinder#26]
Just looked through the release notes.  Looks like in V1.0.2 added support for GWT 2.6.  I didn't see any mention of GWT 2.7.  

Does this currently support GWT 2.7?  

Thanks,
Jake

**Comment by ekuefler** [comment]
It should be - the api is pretty simple and quite stable and doesn't generally have any version dependencies. Try it out and let me know if something doesn't work; it's probably an easy fix if so.

**Comment by tbroyer** [comment]
At least the project builds (tests pass) with 2.7.0.

**Comment by JakeSummers** [comment]
Looks fine on my end.  Thanks for the help.
